apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "technitium.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "technitium.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "technitium.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "technitium.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "technitium.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Always

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ include "technitium.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: dns-tcp
              containerPort: {{ .Values.service.portDnsTcp }}
              protocol: TCP
            - name: dns-udp
              containerPort: {{ .Values.service.portDnsUdp }}
              protocol: UDP
            - name: web
              containerPort: {{ .Values.service.portWeb }}
              protocol: TCP

          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}

          volumeMounts:
            - name: technitium-config
              mountPath: /etc/dns

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.portDnsTcp }}
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.portDnsTcp }}
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3

      volumes:
        - name: technitium-config
          persistentVolumeClaim:
            claimName: {{ include "technitium.fullname" . }}-pvc
